export const Constants = {
  START_SIMULATION: "START_SIMULATION",
  EVENT_SIMULATION_STARTED: "SIMULATION_STARTED",
  EVENT_PIN_MODE: "PIN_MODE",
  EVENT_DIGITAL_PIN: "DIGITAL_PIN_STATUS",
  EVENT_ANALOG_PIN: "ANALOG_PIN_STATUS",
  EVENT_SERIAL: "EVENT_SERIAL",
  COMMAND_SET_DIGITAL: "COMMAND_SET_DIGITAL",
  COMMAND_SET_ANALOG: "COMMAND_SET_ANALOG",
  COMMAND_SEND_SERIAL: "COMMAND_SEND_SERIAL",

  INPUT: 0,
  INPUT_PULLPUP: 1,
  OUTPUT: 2,
  LOW: false,
  HIGH: true,
};